name: Continuous Integration - Security
on:
  pull_request:
    branches:
      - main
      
jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run bandit
        uses: tj-actions/bandit@v5
        with:
          targets: |  # or a single string "."
            .
          options: "-r -s B101,B104"
